!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  host: cwc2.bmc.com
  port: 16196
  runtimeConfig: ic2ga
  stream: GITFLOW
  application: GFLD
  sandbox: Y
  pathMappings:
  - path: "**/Sources/**"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: pli
      ispwType: PLI
    - fileExtension: cpy
      ispwType: COPY
    - fileExtension: incl
      ispwType: INCL
    - fileExtension: jcl
      ispwType: JOB
